---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.add_ldap_account_auth"
      tags:
        - "labocbz.add_ldap_account_auth"
      vars:
        add_ldap_account_auth__ldap_secret: "{{ inv_add_ldap_account_auth__ldap_secret }}"
        add_ldap_account_auth__ldap_base: "{{ inv_add_ldap_account_auth__ldap_base }}"
        add_ldap_account_auth__ldap_address: "{{ inv_add_ldap_account_auth__ldap_address }}"
        add_ldap_account_auth__ldap_rootbinddn: "{{ inv_add_ldap_account_auth__ldap_rootbinddn }}"
        add_ldap_account_auth__ldap_port: "{{ inv_add_ldap_account_auth__ldap_port }}"
      ansible.builtin.include_role:
        name: "labocbz.add_ldap_account_auth"
